[colophon]
= Informazioni su questo eBook

[.text-left]

**Antonio Musarra,** Un trittico vincente: ESP32, Raspberry Pi e EMQ X Edge

[.text-left]

Copertina e impaginazione di Antonio Musarra

Edizione digitale Luglio 2024 (v{revnumber})

Serie: Elettronica&Informatica (#elettronica-informatica)

[.text-left]
Promosso da: Antonio Musarra's Blog (https://www.dontesta.it)

Profilo LinkedIn https://www.linkedin.com/in/amusarra/

[.text-left]
Il progetto di esempio realizzato per quest'opera è disponibile sul repositoy GitHub all'indirizzo https://github.com/amusarra/esp32-mqtt-publish-subscribe

[.text-left]
Quest'opera è la versione eBook dell'articolo pubblicato sul blog di Antonio Musarra all'indirizzo https://www.dontesta.it/en/2021/04/13/esp32-raspberry-pi-emqx-edge-mqtt-publish-subscribe/ nel mese di Aprile 2021.

[.text-left]
Quest'opera è stata realizzata usando l'approccio doc-as-code e il testo è stato scritto in formato AsciiDoc.

Nel caso di errori, segnalazioni o suggerimenti, si prega di aprire una issue o discussione sul repository GitHub.

[.text-left]
Progetto Smart Card Contactless Raspberry Pi

[.text-left]
. Apertura issue https://github.com/amusarra/esp32-mqtt-publish-subscribe/issues
. Apertura discussione https://github.com/amusarra/esp32-mqtt-publish-subscribe/discussions

Nell'ambito del social coding e del contributo alla comunità, è possibile contribuire al progetto con una pull request per migliorare questa guida e il progetto di esempio.

[.text-left]
**Note sul Copyright**
Tutti i diritti d’autore e connessi sulla presente opera appartengono all’autore Antonio Musarra. Per volontà dell’autore quest’opera è rilasciata nei termini della licenza Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International il cui testo integrale è disponibile alla pagina web https://creativecommons.org/licenses/by-nc-sa/4.0/deed.it

Tutti i marchi riportati appartengo ai legittimi proprietari; marchi di terzi, nomi di prodotti, nomi commerciali, nomi corporativi e società citati possono essere marchi di proprietà dei rispettivi titolari o marchi registrati d’altre società e sono stati utilizzati a puro scopo esplicativo e a beneficio del possessore, senza alcun fine di violazione dei diritti di copyright vigenti.